# This file configures the hello-world app which serves public web traffic.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: crawl-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawl-app
  template:
    metadata:
      labels:
        app: crawl-app
    spec:
      containers:
      - name: crawl-container
        image: gcr.io/ev-crawl/crawl-image:latest
        volumeMounts:
        - mountPath: /mnt/fileserver
          name: fileserver2
        env:
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: credentials
                key: GITHUB_TOKEN
      volumes:
      - name: fileserver2
        persistentVolumeClaim:
          claimName: fileserver2-claim
          readOnly: false
